###  ImageOnMap configuration file


# Plugin language. Empty: system language.
# Available: en-US (default, fallback), fr-FR, ru-RU, de-DE, zh-CN, ja-JP, es-ES.
lang:


# Allows collection of anonymous statistics on plugin environment and usage
# The statistics are publicly visible here: http://mcstats.org/plugin/ImageOnMap
collect-data: true

# Displays a message to administrators (ops and console) when a new version is available.
check-for-updates: true


# Images rendered on maps consume Minecraft maps ID, and there are only 2 147 483 647 of them.
# You can limit the maximum number of maps a player, or the whole server, can use with ImageOnMap.
# 0 means unlimited.
map-global-limit: 0
map-player-limit: 0


# Maximum size in pixels for an image to be. 0 is unlimited.
limit-map-size-x: 0
limit-map-size-y: 0


# Should the full image be saved when a map is rendered?
save-full-image: false


# If you want to restrict what domains can be used to download images from, list them below.
# If you don't, leave the list empty.
# Example:
#
# images-hostnames-whitelist:
#  - imgur.com
#  - i.imgur.com
#  - cdn.discordapp.com
images-hostnames-whitelist:

#-------------------------------------------------------------------------------
# Economy

# Enables Vault-compatible economy plugin (requires Vault and a Vault
# compatible economy plugin to work) if set to true
enable-economy: false

# Should the cost to create a splatter map scale with the size of the image?
# i.e. cost-per-map * width * height
# If set to false then the cost to create a splatter map is just the
# cost-per-map no matter what the dimensions of the splatter map are.
scale-map-cost: true

cost-per-map: 100

# Should the cost to copy a splatter map scale with the size of the image?
# This is equivalent to scale-map-cost but is applied whenever the player
# wishes to get a copy of a pre-existing map.
scale-copy-cost: false

# The cost for each copy of the 
cost-per-copy: 50