name: ImageOnMap
main: fr.moribus.imageonmap.ImageOnMap
version: 2.99

commands:
   tomap:
      description: render an image in a map
      usage: /<command> [URL]
   maptool:
      description: manage maps
   maps:
      description: manage maps through a GUI

permissions:
    imageonmap.userender:
        description: Allows you to use /tomap
        default: op